name: Tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: healthsamurai/cljs-drone:23

    steps:
      - uses: actions/checkout@v4
      - run: clojure -X:test
